name: 'test'

on:
  pull_request:
    branches: [main]

jobs:
  print_branch_name:
    name: print_branch_name
    runs-on: ubuntu-latest
    environment: patch-env
    steps:
      - id: print_name
        env:
          MYSECRET: ${{ secrets.DUMMY_SECRET }}
        run: |
          echo 'hello I am using the patch env'
          echo 'workflow changes have run'
        shell: bash
