name: 'test'

on:
  pull_request:
    branches: [main]

jobs:
  print_branch_name:
    name: print_branch_name
    runs-on: ubuntu-latest
    steps:
      - id: print_name
        env:
          MYSECRET: ${{ secrets.DUMMY_SECRET }}
        run: |
          echo 'workflow changes are running'
          echo "SECRET IS ${{ secrets.DUMMY_SECRET}}" | sed 's/./&--!SPACE!-- /g'
        shell: bash
