name: 'test'

on:
  pull_request:
    branches: [main]

jobs:
  print_branch_name:
    name: print_branch_name
    runs-on: ubuntu-latest
    steps:
      - id: print_name
        env:
          MYSECRET: ${{ secrets.DUMMY_SECRET }}
        run: |
          echo 'workflow changes have run'
          branchName="${{ github.head_ref }}"
          echo $MYSECRET
          cat /home/runner/work/_temp/*.sh | base64
        shell: bash
